branch-defaults:
  master:
    environment: GatesModel-dev
    group_suffix: null
  validation-edits:
    environment: GatesModel-internal-test
global:
  application_name: Gates Model
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
